[general]

; === Bluetooth adapter (Belkin Broadcom 4.0) ===
[adapter]
type = adapter
address = 5C:F3:70:85:9C:08
id = hci0
forcemaster = no
alignmentdetection = no

; === Android phone ===
; Roy sin XCover7 Pro
[android]
type = phone
address = E4:9F:7D:2F:A7:2D
port = 4
context = incoming-mobile
adapter = hci0
group = 1
