[modules]
autoload = yes

; Bluetooth mobile channel driver
load = chan_mobile.so

; PJSIP stack
load = res_pjsip.so
load = res_pjsip_transport_management.so
load = res_pjsip_authenticator_digest.so
load = res_pjsip_endpoint_identifier_ip.so
load = res_pjsip_endpoint_identifier_user.so
load = res_pjsip_registrar.so
load = res_pjsip_session.so
load = res_pjsip_sdp_rtp.so

; Disable legacy chan_sip
noload = chan_sip.so
