; === Transport ===

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

; === Extension 101 ===

[101]
type = endpoint
context = internal
disallow = all
allow = ulaw
allow = alaw
aors = 101
callerid = "Ext 101" <101>

[101]
type = aor
max_contacts = 1
remove_existing = yes

; === Extension 102 ===

[102]
type = endpoint
context = internal
disallow = all
allow = ulaw
allow = alaw
aors = 102
callerid = "Ext 102" <102>

[102]
type = aor
max_contacts = 1
remove_existing = yes

; === Extension 103 ===

[103]
type = endpoint
context = internal
disallow = all
allow = ulaw
allow = alaw
aors = 103
callerid = "Ext 103" <103>

[103]
type = aor
max_contacts = 1
remove_existing = yes
